name: Build

on:
  push:
    branches:
      - master
    tags: [ "*" ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Build
        run: sbt compile

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Check Style
        run: sbt check
  
  ci:
    runs-on: ubuntu-20.04
    needs: [ build, lint ]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"        
